### ISSUE TITLE
Design data schema of "workflows".

### ISSUE THREAD

**Issue by shavenking** [andytsai-shaven/project-boomer#7]
``` yaml
order: unsigned integer
title: string
```
- [x] Add docs.

**Comment by shavenking** [comment]
There must be a document about this.

**Comment by shavenking** [comment]
Docs added 8eca3064577ed9f6f64b5cbbbaa0812e16c2e5ac.

**Comment by shavenking** [comment]
> Docs added 8eca306.

This commit does not fit the requirement and shall be redesigned.

**Comment by shavenking** [comment]
- [x] Rewrite docs.

**Comment by shavenking** [comment]
``` yaml
workflows:
    id: increments
    created_at: timestamps
    updated_at: timestamps

workflow_nodes:
    id: increments
    order: unsigned integer
    title: string
    created_at: timestamps
    updated_at: timestamps
```

**Comment by shavenking** [comment]
Docs rewrited f90c8cabd3a989a1575490388c03864d6f46f6e8.

**Comment by shavenking** [comment]
Docs updated 9d7fdda8864c1c8e03a3908aeb03ab12fb67c162.

Fix the absent of `workflow_id` column in table `workflow_nodes`.

``` yaml
workflows:
    id: increments
    created_at: timestamps
    updated_at: timestamps

workflow_nodes:
    id: increments
    workflow_id: unsigned integer
    order: unsigned integer
    title: string
    created_at: timestamps
    updated_at: timestamps
```
